baseURL = 'https://2025.teamleads.kz/'
languageCode = 'ru-RU'
defaultContentLanguage = 'ru'
title = 'Тимлид не кодит - Итоги 2025'
theme = ''
enableRobotsTXT = true
enableGitInfo = false

[languages]
  [languages.ru]
    languageCode = 'ru-RU'
    languageName = 'Русский'
    weight = 1
    [languages.ru.params]
      dateFormat = '2 January 2006'

[params]
  description = '12 месяцев, 26 600 сообщений, одно сообщество'
  author = 'Тимлид не кодит Community'
  year = 2025

  # SEO параметры
  keywords = 'тимлид казахстан, сообщество тимлидов, team lead kz, управление командой разработки, engineering manager, техлид, AI ML в команде, QA тестирование, HR для разработчиков'
  telegram_chat = '@teamleads_kz'
  telegram_url = 'https://t.me/teamleads_kz'

  # Social media
  [params.social]
    telegram = 'https://t.me/teamleads_kz'

  # Organization info для Schema.org
  [params.organization]
    name = 'Тимлид не кодит'
    alternateName = 'teamleads_kz'
    description = 'Крупнейшее русскоязычное сообщество тимлидов, техлидов и engineering managers Казахстана и СНГ'

[build]
  writeStats = true

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = true
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[caches]
  [caches.getjson]
    dir = ':cacheDir/:project'
    maxAge = '24h'
  [caches.getcsv]
    dir = ':cacheDir/:project'
    maxAge = '24h'
  [caches.images]
    dir = ':resourceDir/_gen'
    maxAge = -1
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
